---
- name: Install Required Server Roles for Citrix
  win_feature:
    name: "{{ req_roles }}"
    state: present
  register: requirements

- name: Reboot when Required Roles need a restart
  ansible.windows.win_reboot:
    post_reboot_delay: 120

- name: Map SMB share
  win_shell: |
    net use \\10.10.1.18 "deviceTRUST$" /user:share

- name: create folder
  win_file: 
    path: "C:\\ansible_install"
    state: directory

- name: Copy Citrix iso to the local disk
  win_copy:
    src: "{{ srcisofile }}"
    remote_src: true
    dest: "{{ destisofile }}" 
    force: no

- name: Ensure an ISO is mounted
  win_disk_image: 
    image_path: "{{ destisofile }}"
    state: present
  register: disk_image_out

- name: Run installer from mounted ISO
  win_command: '"{{ exepath }}" {{ params_full }}'
  become: yes
  become_method: runas
  become_flags: logon_type=new_credentials logon_flags=netcredentials_only
  vars:
    ansible_become_user: "{{ dc_admin_domain }}"
    ansible_become_pass: "{{ dc_password_admin }}"
  register: ctxsetup
  run_once: true 

- name: Unmount ISO
  win_disk_image:
    image_path: "{{ destisofile }}"
    state: absent

- name: Reboot when Installation needs a restart
  ansible.windows.win_reboot:
    post_reboot_delay: 120
  when: ctxsetup.reboot_required